# ref: https://jupyterbook.org/en/stable/customize/config.html

title: Insert title of paper here
author: Mia Venezia
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - paperpile_references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
